### ISSUE TITLE
Need for this runner given SpringClassRule and SpringMethodRule?

### ISSUE THREAD

**Issue by mkclemens** [chiknrice/concordion-spring-runner#3]
First off, thank you very much for this project! It got us over a hump several months ago when we needed it.

Since then however we've found that we can get the same effect by using the SpringClassRule and SpringMethodRule approach.

Do you see a role for this runner that the alternate approach doesn't fill? Perhaps Spring versions < 4.2?

It might be worth noting in the readme that the rule based alternative exists for teams that can leverage it.

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/context/junit4/rules/SpringClassRule.html

**Comment by chiknrice** [comment]
Thanks for informing me about this!  I actually need this SpringClassRule for my own project where I need to use Parameterized runner with spring.

This was meant to be a workaround for running concordion with spring but seeing as SpringClassRule is a better approach I would be suggesting the same for projects using spring > 4.2 in the readme.
